### ISSUE TITLE
Error in CreatSWATMF.exe operation

### ISSUE THREAD

**Issue by songyongyu** [spark-brc/QSWATMOD2#2]
An error occured while crearting linkage files, as shown in the figure. The hru_dhru file is also attached.
![error0309_linkage](https://user-images.githubusercontent.com/90433532/157357030-38b43cd3-057f-4984-856d-104e65f9c984.png)
[hru_dhru.zip](https://github.com/spark-brc/QSWATMOD2/files/8210984/hru_dhru.zip)

**Comment by spark-brc** [comment]
Do you still have this issue?

**Comment by spark-brc** [comment]
Thanks for the report. Mismatching columns or rows might cause this issue. Please, refer to this information (https://github.com/spark-brc/QSWATMOD2#add-or-subtract-rows-and-columns).
