### ISSUE TITLE
LATEST VERSION OF QSWATMOD SHOWING ERROR DURING "PUMPING RATE DICTATED BY SWAT"

### ISSUE THREAD

**Issue by Diwakarbhai** [spark-brc/QSWATMOD2#3]
@spark-brc 
I have been trying to apply QSWATMOD v2.0, v2.0.2 and the recently released v2.3.0 on your tutorial and your dataset. When using QSWATMOD on the Dataset mentioned in the tutorial, in the Simulation Tab, during "Pumping Rate Dictated by SWAT", when I click on "Point shapefile", QGIS shows an error saying "QSettings not defined". The exact error is: 

An error has occurred while executing Python code:

NameError: name 'QSettings' is not defined

Traceback (most recent call last):
  File "C:/Users/hp/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\QSWATMOD2\QSWATMOD2.py", line 897, in use_irrig_swat_pts
    config_sets.use_irrig_swat_pts(self)
  File "C:/Users/hp/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\QSWATMOD2\pyfolder\config_sets.py", line 462, in use_irrig_swat_pts
    settings = QSettings()
NameError: name 'QSettings' is not defined

Python version: 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)]
QGIS version: 3.16.16-Hannover Hannover, f5778a89df

Python Path:

C:/PROGRA~1/QGIS3~1.16/apps/qgis-ltr/./python
C:/Users/hp/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/hp/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
C:/PROGRA~1/QGIS3~1.16/apps/qgis-ltr/./python/plugins
C:\PROGRA~1\QGIS3~1.16\apps\Python37
C:\PROGRA~1\QGIS3~1.16\apps\Python37\Scripts
C:\Program Files\QGIS 3.16\bin\python37.zip
C:\PROGRA~1\QGIS3~1.16\apps\Python37\DLLs
C:\PROGRA~1\QGIS3~1.16\apps\Python37\lib
C:\Program Files\QGIS 3.16\bin
C:\PROGRA~1\QGIS3~1.16\apps\Python37\lib\site-packages
C:\PROGRA~1\QGIS3~1.16\apps\Python37\lib\site-packages\win32
C:\PROGRA~1\QGIS3~1.16\apps\Python37\lib\site-packages\win32\lib
C:\PROGRA~1\QGIS3~1.16\apps\Python37\lib\site-packages\Pythonwin
C:/Users/hp/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/hp/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\QSWAT3_64\QSWAT

Moreover, I have tried several techniques, such as keeping the length of the fields "h01", "h02", and "h03" in the attribute table of irrig_mf as small as 0 to as high as 10 during different trial runs. In each case I am getting the same error.
The screenshot has been attached below. 

![Screenshot (150)](https://user-images.githubusercontent.com/111201515/184509925-32385e7f-99a3-477b-885d-795d405151b8.png)

Also, I am attaching the link to my work, so that the discrepancies can be checked.

https://drive.google.com/file/d/1n4mgpLzh1AJCa5652OqkTQM2ujtOC9gI/view?usp=sharing  

I would be highly obliged if I am helped in successfully running the tutorial. This plugin forms an integral part of my research work.

**Comment by spark-brc** [comment]
Thanks for the report. The issue was fixed by defining 'QSettings' in version 2.3.1.

**Comment by spark-brc** [comment]
Thanks for the report. The issue was fixed by defining 'QSettings' in version 2.3.1.
