### ISSUE TITLE
LATEST VERSION OF QSWATMOD NOT WORKING

### ISSUE THREAD

**Issue by Diwakarbhai** [spark-brc/QSWATMOD2#4]
Hello Sir,
I installed the latest version of QSWATMOD and used the MBRW dataset to run the demo. However, I am facing 2 problems:

The dataset shared by you does not consist of the MODFLOW model folder for MBRW. As a result, while defining the path of MODFLOW model, I am not able to define the MODFLOW folder. Henceforth, can you please share the MODFLOW model corresponding to MBRW?
When trying to use the 3rd option, where QSWATMOD creates a simple MODFLOW model by itself, QSWATMOD displays an error as follows:

An error has occurred while executing Python code: 

AttributeError: type object 'QPalette' has no attribute 'PlaceholderText' 
Traceback (most recent call last):
  File "C:/Users/hp/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\QSWATMOD2\QSWATMOD2.py", line 1920, in showCreateMFmodel_dialog
    self.dlgMF = createMFmodel_dialog.createMFmodelDialog(self.iface)
  File "C:/Users/hp/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\QSWATMOD2\dialogs\createMFmodel_dialog.py", line 62, in __init__
    self.setupUi(self)
  File "", line 255, in setupUi
AttributeError: type object 'QPalette' has no attribute 'PlaceholderText'

Python version: 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)] 
QGIS version: 3.16.16-Hannover Hannover, f5778a89df 

Python Path:
C:/PROGRA~1/QGIS3~1.16/apps/qgis-ltr/./python
C:/Users/hp/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/hp/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
C:/PROGRA~1/QGIS3~1.16/apps/qgis-ltr/./python/plugins
C:\PROGRA~1\QGIS3~1.16\apps\Python37
C:\PROGRA~1\QGIS3~1.16\apps\Python37\Scripts
C:\Program Files\QGIS 3.16\bin\python37.zip
C:\PROGRA~1\QGIS3~1.16\apps\Python37\DLLs
C:\PROGRA~1\QGIS3~1.16\apps\Python37\lib
C:\Program Files\QGIS 3.16\bin
C:\PROGRA~1\QGIS3~1.16\apps\Python37\lib\site-packages
C:\PROGRA~1\QGIS3~1.16\apps\Python37\lib\site-packages\win32
C:\PROGRA~1\QGIS3~1.16\apps\Python37\lib\site-packages\win32\lib
C:\PROGRA~1\QGIS3~1.16\apps\Python37\lib\site-packages\Pythonwin
C:/Users/hp/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/hp/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\QSWAT3_64\QSWAT

Please find attached the screenshot of the error.

If convenient and possible, please help me in fixing this problem. I find the errors extremely worrying since my Thesis work is based on SW-GW analysis using QSWATMOD. 

Waiting eagerly for your reply.

![QSWAT_Error](https://user-images.githubusercontent.com/111201515/192138656-d4aa4ebd-db8e-43d8-9370-a9ab5b78e3a6.png)

**Comment by spark-brc** [comment]
Did you install the latest version (2.3.1)? It's because I couldn't find the error message when I clicked the "Create a Simple MODFLOW model" button.
![image](https://user-images.githubusercontent.com/17608997/194948943-e6f44567-bc38-45b9-8d21-78a9d124b17d.png)

**Comment by Diwakarbhai** [comment]
Yes sir, I had installed the latest version i.e., version 2.3 of QSWATMOD.
Still, the error was coming. Please find attached the screenshot of the
same.
May I know which version of QGIS are you using? I am using QGIS 3.16.16.

Yours sincerely,
Diwakar

**Comment by Diwakarbhai** [comment]
Hello Sir,
May I know, which version of QGIS are you using in conjunction with
QSWATMOD version 2.3?? I am waiting for your reply, since I will install
the same QSWATMOD version in the same QGIS version as yours and try
creating the MODFLOW model in QSWATMOD as soon as possible.

Waiting eagerly for your reply,
Yours sincerely,
Diwakar Saran

**Comment by spark-brc** [comment]
Please update your QGIS to the latest long-term release version.

**Comment by Diwakarbhai** [comment]
Thank you sir, I have updated my QGIS to v 3.22.6. Now the option is
working. Thank you for your advice!!
