### ISSUE TITLE
Couldn't load plugin 'QSWATMOD2' due to an error when calling its classFactory() method 

### ISSUE THREAD

**Issue by L14996** [spark-brc/QSWATMOD2#5]
![image](https://user-images.githubusercontent.com/60312352/237033144-6e84805f-8a27-463d-974e-5a5b342e28e7.png)

**Comment by spark-brc** [comment]
Please try it with a long-term release version (3.28). https://www.qgis.org/en/site/forusers/alldownloads.html

**Comment by liorange523** [comment]
> I apologize for the inconvenience. I need to update some libraries to work with QGIS 3.28 version. Please use QGIS 3.22. Here is a link. https://download.qgis.org/downloads/QGIS-OSGeo4W-3.22.16-1.msi

Hello, I also encountered this problem, but I am using the QGIS3.32 version, how to solve it？
